### ISSUE TITLE
Not working with Zabbix 4.0.4

### ISSUE THREAD

**Issue by drGrabol** [disc/zabbix-sender#11]
Not working with version Zabbix 4.0.4
15964:20190210:005912.664 Message size 1701978747 from 1.1.1.1 exceeds the maximum size 134217728 bytes. Message ignored.
 15964:20190210:005912.664 Message size 1701978747 from 1.1.1.1 exceeds the maximum size 134217728 bytes. Message ignored.
 15965:20190210:005912.665 Message size 1701978747 from 1.1.1.1 exceeds the maximum size 134217728 bytes. Message ignored.
 15967:20190210:005912.665 Message size 1701978747 from 1.1.1.1 exceeds the maximum size 134217728 bytes. Message ignored.
 15966:20190210:005912.665 Message size 1701978747 from 1.1.1.1 exceeds the maximum size 134217728 bytes. Message ignored.
 15968:20190210:005912.666 Message size 1701978747 from 1.1.1.1 exceeds the maximum size 134217728 bytes. Message ignored.
 15968:20190210:005912.666 Message size 1701978747 from 1.1.1.1 exceeds the maximum size 134217728 bytes. Message ignored.
 15968:20190210:005912.666 Message size 1701978747 from 1.1.1.1 exceeds the maximum size 134217728 bytes. Message ignored.
 15968:20190210:005912.666 Message size 1701978747 from 1.1.1.1 exceeds the maximum size 134217728 bytes. Message ignored.
 15966:20190210:005912.666 Message size 1701978747 from 1.1.1.1 exceeds the maximum size 134217728 bytes. Message ignored.
 15966:20190210:005912.667 Message size 1701978747 from 1.1.1.1 exceeds the maximum size 134217728 bytes. Message ignored.
 15970:20190210:005912.739 Message size 1701978747 from 1.1.1.2 exceeds the maximum size 134217728 bytes. Message ignored.
 15965:20190210:005913.045 Message size 1701978747 from 1.1.1.2 exceeds the maximum size 134217728 bytes. Message ignored.
 15964:20190210:005913.354 Message size 1701978747 from 1.1.1.2 exceeds the maximum size 134217728 bytes. Message ignored.
 15966:20190210:005913.851 Message size 1701978747 from 1.1.1.2 exceeds the maximum size 134217728 bytes. Message ignored.
 15968:20190210:005914.141 Message size 1701978747 from 1.1.1.2 exceeds the maximum size 134217728 bytes. Message ignored.
 15964:20190210:005914.427 Message size 1701978747 from 1.1.1.2 exceeds the maximum size 134217728 bytes. Message ignored.
 15968:20190210:005914.853 Message size 1701978747 from 1.1.1.2 exceeds the maximum size 134217728 bytes. Message ignored.

**Comment by disc** [comment]
The error says that your message size is more than 128 MiB limit. You can try to increase this limit in Zabbix server config. I guess it's not a sender issue.

**Comment by drGrabol** [comment]
I can read the message, but it is not true. 
Please, do not 'guess'. 
According to Zabbix documentation I change the line from:
`$packet = "ZBXD\1" . pack('P', strlen($data)) . $data;`
to
`$packet = "ZBXD\1" . pack('V', strlen($data)) . "\0\0\0\0" . $data;`
and it start working.

**Comment by disc** [comment]
As I see there is two way of a header building - https://www.zabbix.com/documentation/4.0/manual/appendix/protocols/header_datalen
I will replace exists way to the second one. Thanks for your feedback.
