### ISSUE TITLE
Doesn't work on PHP 5.3

### ISSUE THREAD

**Issue by marki555** [disc/zabbix-sender#13]
In description you say it works in PHP 5.3. But you use short array tags `[]` (instead of `array()`), which were introduced only in PHP 5.4.
The fix is easy - change `[]` to `array()` in few places where arrays are initialized + few other places where data is assigned to them.

I know it makes no sense to make such changes to support a PHP version which is EOL for many years (although I still got it on one legacy server), so I suggest to change the README and add a link to this issue in case someone needs to run it on PHP 5.3 also...

**Comment by disc** [comment]
Hey @marki555 you're right, it doesn't make change to support that version. so I've just updated **README** and **composer.json** in this commit https://github.com/disc/zabbix-sender/commit/e3e1e72b470d6b03a9bace32e2f99149dbd9a416
