### ISSUE TITLE
Add code coverage for unit tests

### ISSUE THREAD

**Issue by disc** [disc/zabbix-sender#2]
I'd like to see what percent of code has tests coverage.
If possible add code coverage for unit test in Travis CI.

**Comment by fr05t1k** [comment]
I'll take it

**Comment by narendravaghela** [comment]
@disc You can use https://codecov.io for coverage report.
See https://codecov.io/github/cakephp/cakephp for reference.

**Comment by disc** [comment]
@fr05t1k @narendravaghela Nice work, thanks!
