### ISSUE TITLE
socketReceive does not work

### ISSUE THREAD

**Issue by marki555** [disc/zabbix-sender#7]
`$this->socketReceive` returns the return value of php function `socket_recv()`, which according to documentation returns number of bytes received (and not data received). https://secure.php.net/manual/en/function.socket-recv.php

However function `$this->parseResponse` assigns it to `$response` and tries to parse it which fails.
Or does it work for you? I am trying it on old server with PHP 5.3, but don't see anything in PHP manual what could make `socket_recv()` return the data instead of number of bytes in higher PHP versions...

Fix is to return `$response` from `socketReceive` (or something better which would return true/false and assign the data to some variable for further processing - like `$this->raw_response`).

**Comment by disc** [comment]
Hey @marki555, you're right, there is a mistake.
The method should return a data instead of the length of this data.
I'll fix it asap.
